image: centos:centos7.3.1611

variables:
  ANDROID_TARGET_SDK: "25"
  ANDROID_BUILD_TOOLS: "25.0.2"
  ANDROID_SDK_TOOLS: "25.2.5"

before_script:
  - yum --quiet update -y
  - yum --quiet -y install java-1.8.0-openjdk-devel
  - yum --quiet install -y glibc.i686 zlib.i686 libstdc++.i686 ncurses-libs.i686
  - yum install -y wget unzip
  - wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/tools_r${ANDROID_SDK_TOOLS}-linux.zip 
  - unzip -q android-sdk.zip -d $PWD/android-sdk-linux
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter android-${ANDROID_TARGET_SDK}
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter platform-tools
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter build-tools-${ANDROID_BUILD_TOOLS}
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter extra-android-m2repository
  - echo y | android-sdk-linux/tools/android --silent update sdk --no-ui --all --filter extra-google-m2repository
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk
  - chmod +x ./gradlew

build:
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/apk/